name: upload-cloud-storage Integration

on: [push, pull_request]

jobs:
  gcloud:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name }}
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: build
        name: Build dist
        run: |-
          npm install
          npm run build
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.UPLOAD_CLOUD_STORAGE_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.UPLOAD_CLOUD_STORAGE_GCP_SA_KEY_B64 }}
          export_default_credentials: true
      - name: make temp folder and file
        run: |
          mkdir -p test
          touch test/test2.txt
      - id: upload
        name: upload file
        uses: ./
        with:
          path: ./test/test2.txt
          destination: ${{ secrets.UPLOAD_CLOUD_STORAGE_TEST_BUCKET }}/testprefix
      - name: get output
        run: echo '${{ steps.upload.outputs.uploaded }}'

  b64_json:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name }}
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: build
        name: Build dist
        run: |-
          npm install
          npm run build
      - name: make temp folder and files
        run: |
          mkdir -p test
          touch test/test1.txt
          touch test/test2.txt
      - id: upload
        name: upload folder
        uses: ./
        with:
          path: ./test
          destination: ${{ secrets.UPLOAD_CLOUD_STORAGE_TEST_BUCKET }}/testprefix
          credentials: ${{ secrets.UPLOAD_CLOUD_STORAGE_GCP_SA_KEY_B64 }}
      - name: get output
        run: echo '${{ steps.upload.outputs.uploaded }}'

  json:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name }}
    name: with json creds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: build
        name: Build dist
        run: |-
          npm install
          npm run build
      - name: make temp folder and files
        run: |
          mkdir -p test
          touch test/test1.txt
          touch test/test2.txt
      - id: upload
        name: upload folder
        uses: ./
        with:
          path: ./test
          destination: ${{ secrets.UPLOAD_CLOUD_STORAGE_TEST_BUCKET }}/testprefix
          credentials: ${{ secrets.UPLOAD_CLOUD_STORAGE_GCP_SA_KEY_JSON }}
      - name: get output
        run: echo '${{ steps.upload.outputs.uploaded }}'

  mocha-it:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name }}
    name: mocha integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.UPLOAD_CLOUD_STORAGE_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.UPLOAD_CLOUD_STORAGE_GCP_SA_KEY_B64 }}
          export_default_credentials: true
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run lint

      - name: npm test
        run: npm run test
        env:
          UPLOAD_CLOUD_STORAGE_TEST_BUCKET: ${{ secrets.UPLOAD_CLOUD_STORAGE_TEST_BUCKET }}
